//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mrHelper.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mrHelper.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Balls {
            get {
                object obj = ResourceManager.GetObject("Balls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DefaultAppIcon {
            get {
                object obj = ResourceManager.GetObject("DefaultAppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///   width: 100%;
        ///   margin: 0;
        ///}
        ///
        ///body div { 
        ///   font-family: Microsoft Sans Serif, Sans Serif;
        ///   padding: 1px;
        ///   border: 1px solid white;
        ///}
        ///
        ///table {
        ///   border: solid 1px #DDEEEE;
        ///   border-collapse: collapse;
        ///   border-spacing: 0;
        ///}
        ///
        ///table thead th {
        ///   background-color: #E4E7E6;
        ///   border: solid 1px #DDEEEE;
        ///   color: #333;
        ///   padding: 5px;
        ///   text-align: left;
        ///   text-shadow: 1px 1px 1px #fff;
        ///}
        ///
        ///table tbody td {
        ///   background-color: #FBFBF5;
        ///   border: solid 1px #DDEE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DiscussionNoteCSS {
            get {
                return ResourceManager.GetString("DiscussionNoteCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HappyNY2020 {
            get {
                object obj = ResourceManager.GetObject("HappyNY2020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///   width: 100%;
        ///   margin: 0;
        ///}
        ///
        ///body div { 
        ///   font-family: Microsoft Sans Serif, Sans Serif;
        ///   padding: 1px;
        ///   border: 1px solid white;
        ///}
        ///
        ///table {
        ///   border: solid 1px #DDEEEE;
        ///   border-collapse: collapse;
        ///   border-spacing: 0;
        ///}
        ///
        ///table thead th {
        ///   background-color: #E4E7E6;
        ///   border: solid 1px #DDEEEE;
        ///   color: #333;
        ///   padding: 5px;
        ///   text-align: left;
        ///   text-shadow: 1px 1px 1px #fff;
        ///}
        ///
        ///table tbody td {
        ///   background-color: #FBFBF5;
        ///   border: solid 1px #DDEE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MergeRequestDescriptionCSS {
            get {
                return ResourceManager.GetString("MergeRequestDescriptionCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///  background-image: url(&apos;balls.png&apos;);
        ///  background-repeat: repeat-x;
        ///  background-attachment: fixed;
        ///  background-position: 0 0;
        ///  padding-top: 50px;
        ///}
        ///
        ///.
        /// </summary>
        internal static string NewYear2020_CSS {
            get {
                return ResourceManager.GetString("NewYear2020_CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Penguin {
            get {
                object obj = ResourceManager.GetObject("Penguin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PleaseInspect {
            get {
                object obj = ResourceManager.GetObject("PleaseInspect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SnowflakeBg {
            get {
                object obj = ResourceManager.GetObject("SnowflakeBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tree {
            get {
                object obj = ResourceManager.GetObject("Tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
